---
- name: Include secrets
  include_vars:
    file: "../vars/secrets.yml"

- name: Inject ldap settings
  ansible.controller.settings:
    settings: "{{ lookup('file','../vars/ldap.json') | from_json }}"

- name: Set the LDAP Auth Bind Password
  ansible.controller.settings:
    name: "AUTH_LDAP_BIND_PASSWORD"
    value: "{{ AUTH_LDAP_BIND_PASSWORD }}"

